### PR TITLE
Compile examples as a first of smoke test

### PR DESCRIPTION
**Pull request by traversaro**
Enable compilation of tests to check that everything is working as expected. As the final artefact will be exactly the same, I did not bumper the build number on this one.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Switching to vs2019 seems to fix the compilation problems.

**Comment by h-vetinari** [comment]
Cool, thanks a lot!

**Pull request merged**
